# Generated by Django 4.0.2 on 2022-02-07 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField(verbose_name='phone number')),
                ('birthdate', models.DateField(verbose_name='birth date')),
                ('gender', models.IntegerField(choices=[(0, 'not specified'), (1, 'male'), (2, 'female'), (3, 'other')], default=0)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_psycologist', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
