# Generated by Django 4.0.2 on 2022-02-07 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_account_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=10, verbose_name='phone number')),
                ('profile_picture', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_psycologist',
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(max_length=10, verbose_name='phone number'),
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1500)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
    ]
