# Generated by Django 4.0.2 on 2022-02-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_employee_remove_client_is_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="profile_picture",
            field=models.URLField(default=""),
        ),
    ]
