# Generated by Django 3.1.14 on 2022-03-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0007_auto_20220303_1502"),
    ]

    operations = [
        migrations.CreateModel(
            name="PsychologicalDisorder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FieldOfExpertise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psychological_disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symptom.psychologicaldisorder",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.psychologist",
                    ),
                ),
            ],
            options={
                "unique_together": {("psychologist", "psychological_disorder")},
            },
        ),
        migrations.CreateModel(
            name="Feel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.client"
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symptom.symptom",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "symptom")},
            },
        ),
        migrations.CreateModel(
            name="CharacterizedBy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "psychological_disorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symptom.psychologicaldisorder",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="symptom.symptom",
                    ),
                ),
            ],
            options={
                "unique_together": {("psychological_disorder", "symptom")},
            },
        ),
    ]
