# Generated by Django 3.1.14 on 2022-02-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20220220_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, unique='True')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('confirmation_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.confirmationstatus')),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.psychologist')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='GoesTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='Fullcalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=50)),
                ('confirmation_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.confirmationstatus')),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.psychologist')),
            ],
        ),
    ]
