# Generated by Django 3.1.14 on 2022-02-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='WorkingHours',
        ),
        migrations.RenameField(
            model_name='therapy',
            old_name='schedule_id',
            new_name='workinghours_id',
        ),
    ]
