# Generated by Django 3.1.14 on 2022-02-25 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220220_1407'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullcalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=50)),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.psychologist')),
            ],
        ),
    ]
