# Generated by Django 3.1.14 on 2022-02-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_fullcalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapy',
            old_name='shedule_id',
            new_name='schedule_id',
        ),
    ]
