# Generated by Django 3.1.14 on 2022-02-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20220225_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcalendar',
            name='confirmation',
            field=models.CharField(default='not yet', max_length=15),
        ),
        migrations.AddField(
            model_name='therapy',
            name='confirmation',
            field=models.CharField(default='not yet', max_length=15),
        ),
    ]
