# Generated by Django 3.1.14 on 2022-02-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220220_1407'),
        ('scheduler', '0004_auto_20220226_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoesTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.psychologist')),
            ],
        ),
    ]
