# Generated by Django 3.1.14 on 2022-02-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220220_1407'),
        ('scheduler', '0005_goesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goesto',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client', unique='True'),
        ),
    ]
